# Generated by Django 5.2.1 on 2025-05-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
